import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';
import { enUS } from '@clerk/localizations'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
 
    appearance={{
      
      elements: {
        formButtonPrimary: 'bg-blue-600 text-white',
        cardBox: 'bg-white shadow-lg',
        footer: 'bg-white border-t border-900 text-white',
        footerActionLink: 'text-blue-600',
      },
      layout: {
        socialButtonsPlacement: 'bottom',
        socialButtonsVariant: 'iconButton',
        termsPageUrl: 'https://clerk.com/terms'
      }
    }}
  >
  
    
    
      <html lang='en'>
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}